services:
  runner:
    image: allanrogerreid/github-runner-image:latest 
    restart: always 
    environment:
      - OWNER_REPO_OR_ORG=repos/<user>/<repo-name>
      - GH_TOKEN=<pat>
      - GH_RUNNER_USER=docker
      - GH_RUNNER_OPTIONS=--labels self-hosted --no-default-labels
    deploy:
      mode: replicated
      replicas: 4 
      resources:
        limits:
          cpus: '0.25' 
          memory: 256M 
        reservations:
          cpus: '0.10'
          memory: 128M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker